version: "3.5"

services:
  app:
    environment:
      - SENTRY_ENV=development
      - SENTRY_SAMPLE_RATE=0
      - LOG_LEVEL=DEBUG
    env_file:
      - app.env
    ports:
      - "8282:8282"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8282 -jar app.jar

  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=<crime_court_message_processor>